build(pnpm): Remove workspace protocol to allow singleton package useage

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,4 +1,10 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-npm run type-check
+if [ ! -e "pnpm-lock.yaml" ]; then
+    echo "pnpm-lock.yaml is missing! `pnpm install` and `git commit --ammend` to fix."
+    exit 1
+fi
+
+pnpm install --frozen-lockfile
+pnpm run type-check
